"""empty message

Revision ID: dfdd4981b6cb
Revises: 8f746f65e063
Create Date: 2020-09-07 00:19:56.536502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdd4981b6cb'
down_revision = '8f746f65e063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('full_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'full_name')
    # ### end Alembic commands ###
